// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Ume_LJiA6Jxoa109fRtXTkl-2FGpbyE',
    appId: '1:967214092995:web:ebef357367c66cd56bc876',
    messagingSenderId: '967214092995',
    projectId: 'kigali-connect-3c3be',
    authDomain: 'kigali-connect-3c3be.firebaseapp.com',
    storageBucket: 'kigali-connect-3c3be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLkJPRoRJSH4UrQ5A1OsAO0dCVpKXVuGA',
    appId: '1:967214092995:android:734fa2a3e53e4e726bc876',
    messagingSenderId: '967214092995',
    projectId: 'kigali-connect-3c3be',
    storageBucket: 'kigali-connect-3c3be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpsNE8IlmnfuE5OAFZXPIpEpCpZ2pEiQ',
    appId: '1:967214092995:ios:e67e040b5090f7c66bc876',
    messagingSenderId: '967214092995',
    projectId: 'kigali-connect-3c3be',
    storageBucket: 'kigali-connect-3c3be.firebasestorage.app',
    iosBundleId: 'com.example.kigaliConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpsNE8IlmnfuE5OAFZXPIpEpCpZ2pEiQ',
    appId: '1:967214092995:ios:e67e040b5090f7c66bc876',
    messagingSenderId: '967214092995',
    projectId: 'kigali-connect-3c3be',
    storageBucket: 'kigali-connect-3c3be.firebasestorage.app',
    iosBundleId: 'com.example.kigaliConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Ume_LJiA6Jxoa109fRtXTkl-2FGpbyE',
    appId: '1:967214092995:web:0d0cf78bf94cfd2d6bc876',
    messagingSenderId: '967214092995',
    projectId: 'kigali-connect-3c3be',
    authDomain: 'kigali-connect-3c3be.firebaseapp.com',
    storageBucket: 'kigali-connect-3c3be.firebasestorage.app',
  );
}
